services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    cpus: 0.50
    mem_limit: 512m

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-bankuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-bankpass}

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bank-service:
    image: bank-service:1.0
    restart: unless-stopped
    cpus: 1.00
    mem_limit: 768m

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

    ports:
      - "127.0.0.1:8082:8082"

    environment:
      SERVER_PORT: 8082

      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-bankdb}
      DATABASE_USERNAME: ${POSTGRES_USER:-bankuser}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-bankpass}

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-bankuser}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bankpass}



    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    cpus: 0.50
    mem_limit: 512m

    ports:
      - "127.0.0.1:5432:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bankdb}
      POSTGRES_USER: ${POSTGRES_USER:-bankuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bankpass}

    volumes:
      - postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  rabbitmq-data:
  postgres-data:
