CREATE TABLE app_user(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    current_state VARCHAR(20) NOT NULL,

    CONSTRAINT chk_app_user_role
        CHECK (role IN ('ADMIN', 'CUSTOMER')),

    CONSTRAINT chk_app_user_state
        CHECK (current_state IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE bank_account(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255) NOT NULL UNIQUE,
    namely VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    balance DOUBLE PRECISION NOT NULL,

    CONSTRAINT fk_bank_account_user
    FOREIGN KEY(user_id)
    REFERENCES app_user(id)
);




